apiVersion: apps/v1
kind: Deployment
metadata:
  name: tangerine-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: tangerine-frontend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 33%
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app.kubernetes.io/name: tangerine-frontend
    spec:
      containers:
        - name: tangerine-frontend
          image: quay.io/redhat-user-workloads/hcm-eng-prod-tenant/tangerine/tangerine-frontend
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 3
          resources:
            requests:
              cpu: 250m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 128Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          securityContext:
            capabilities: {}
            privileged: false
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
