---
kind: Template
apiVersion: template.openshift.io/v1
metadata:
  name: tangerine-frontend

parameters:
- name: IMAGE
  value: quay.io/tangerine/tangerine-frontend:latest
- name: IMAGE_TAG
  value: latest
- name: CPU_LIMIT
  value: 500m
- name: MEMORY_LIMIT
  value: 128Mi
- name: CPU_REQUEST
  value: 250m
- name: MEMORY_REQUEST
  value: 128Mi

objects:
# tangerine frontend
- kind: Deployment
  apiVersion: apps/v1
  metadata:
    name: tangerine-frontend
  spec:
    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 33%
    minReadySeconds: 5
    replicas: 1
    selector:
      matchLabels:
        app.kubernetes.io/name: tangerine-frontend
    template:
      metadata:
        labels:
          app.kubernetes.io/name: tangerine-frontend
      spec:
        containers:
          - resources:
              requests:
                memory: ${MEMORY_REQUEST}
                cpu: ${CPU_REQUEST}
              limits:
                memory: ${MEMORY_LIMIT}
                cpu: ${CPU_LIMIT}
            readinessProbe:
              tcpSocket:
                port: 3000
              initialDelaySeconds: 5
              periodSeconds: 5
              timeoutSeconds: 1
              successThreshold: 1
              failureThreshold: 3
            livenessProbe:
              tcpSocket:
                port: 3000
              initialDelaySeconds: 5
              periodSeconds: 5
              timeoutSeconds: 1
              successThreshold: 1
              failureThreshold: 3
            terminationMessagePath: /dev/termination-log
            name: tangerine-frontend
            securityContext:
              capabilities: {}
              privileged: false
            ports:
              - containerPort: 3000
                protocol: TCP
            imagePullPolicy: IfNotPresent
            terminationMessagePolicy: File
            image: ${IMAGE}:${IMAGE_TAG}
        restartPolicy: Always
        terminationGracePeriodSeconds: 30
        dnsPolicy: ClusterFirst
        securityContext: {}
        schedulerName: default-scheduler

- kind: Service
  apiVersion: v1
  metadata:
    name: tangerine-frontend
    labels:
      app.kubernetes.io/name: tangerine-frontend
  spec:
    selector:
      app.kubernetes.io/name: tangerine-frontend
    ports:
      - name: tangerine-frontend
        protocol: TCP
        port: 3000
        targetPort: 3000

